In [2]:
import numpy as np
import cv2

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline
import pickle

from os import listdir
from os.path import isfile, join



In [3]:
calDir = '.\\camera_cal'
calFiles = [f for f in listdir(calDir) if isfile(join(calDir, f))]

for i in range(0,len(calFiles)-1):
    fullFileName = calDir + '\\' + calFiles[i]
    #print (fullFileName)
    img = mpimg.imread(fullFileName)
    #plt.imshow(img)
    
    objpoints=[] #3D points in real world
    imgpoints=[] #2D points in image
    
    #prepare obj points (0,0,0), (1,0,0) (2,0,0)....(9,6,0)
    objp = np.zeros((6*9,3), np.float32)
    objp[:,:2] = np.mgrid[0:9, 0:6].T.reshape(-1,2)
    
    # convert to gray scale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #find the chessboard corners
    ret, corners = cv2.findChessboardCorners(gray, (9,6), None)
    
    # when corners found, add object points, image points
    if ret == True:
        imgpoints.append(corners)
        objpoints.append(objp)
        
        #img = cv2.drawChessboardCorners(img, (9,6), corners, ret)
        #plt.imshow(img)
        #plt.show()
        

In [4]:
# ret - 
# mtx - cam matrix to transform 3D obj point to 2D image point
# dist - distortion coeff
# rvecs, tvecs - camera position in the world, rotation and translation pos
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [5]:
print (ret)
print (mtx)

calPickle = open ('calib.p', 'wb')
pickle.dump([ret, mtx, dist, rvecs, tvecs], calPickle)
calPickle.close()




0.6101385536433866
[[  1.00391208e+03   0.00000000e+00   6.30724865e+02]
 [  0.00000000e+00   1.08034061e+03   3.52424736e+02]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]


In [6]:


src = np.float32(
    [  [690 ,450],
       [920 ,600],               
       [380 , 600 ],
       [595 , 450]
    ]
    )

dst = np.float32(
    [  [1050 , 50  ],
       [1050 , 700 ],               
       [150 , 700 ],
       [150 , 50  ]
     
    ]
    )

M = cv2.getPerspectiveTransform(src, dst)
img_size = (int(img.shape[1]), int(img.shape[0]-10))


calPickle = open ('pTrans.p', 'wb')
pickle.dump([M, img_size, src, dst], calPickle)
calPickle.close()